//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Employee.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首次签到.
        /// </summary>
        public static string IDS_CHECKIN {
            get {
                return ResourceManager.GetString("IDS_CHECKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 末次签到.
        /// </summary>
        public static string IDS_CHECKOUT {
            get {
                return ResourceManager.GetString("IDS_CHECKOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期.
        /// </summary>
        public static string IDS_DATE {
            get {
                return ResourceManager.GetString("IDS_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每月小计.
        /// </summary>
        public static string IDS_FLEXABLE {
            get {
                return ResourceManager.GetString("IDS_FLEXABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simsun.
        /// </summary>
        public static string IDS_FONT_FAMILY {
            get {
                return ResourceManager.GetString("IDS_FONT_FAMILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弹性时间.
        /// </summary>
        public static string IDS_FREE_TIME {
            get {
                return ResourceManager.GetString("IDS_FREE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 五.
        /// </summary>
        public static string IDS_FRIDAY {
            get {
                return ResourceManager.GetString("IDS_FRIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一.
        /// </summary>
        public static string IDS_MONDAY {
            get {
                return ResourceManager.GetString("IDS_MONDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        public static string IDS_NAME {
            get {
                return ResourceManager.GetString("IDS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请注意：如果考勤时间不同步请向公司前台要求进行数据回收.
        /// </summary>
        public static string IDS_NOTICE {
            get {
                return ResourceManager.GetString("IDS_NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        public static string IDS_QUERY {
            get {
                return ResourceManager.GetString("IDS_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 六.
        /// </summary>
        public static string IDS_SATURDAY {
            get {
                return ResourceManager.GetString("IDS_SATURDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 防火墙穿透（SDCC专用）.
        /// </summary>
        public static string IDS_SDCC_FW_TRANSMISSION_MODE {
            get {
                return ResourceManager.GetString("IDS_SDCC_FW_TRANSMISSION_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法连接到服务器.
        /// </summary>
        public static string IDS_SERVER_UNAVAILABLE {
            get {
                return ResourceManager.GetString("IDS_SERVER_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据处理中…….
        /// </summary>
        public static string IDS_STANDBY {
            get {
                return ResourceManager.GetString("IDS_STANDBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日.
        /// </summary>
        public static string IDS_SUNDAY {
            get {
                return ResourceManager.GetString("IDS_SUNDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四.
        /// </summary>
        public static string IDS_THURSDAY {
            get {
                return ResourceManager.GetString("IDS_THURSDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 考勤查询 -- 码农不是万能的，但是没有码农是万万不能的.
        /// </summary>
        public static string IDS_TITLE {
            get {
                return ResourceManager.GetString("IDS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二.
        /// </summary>
        public static string IDS_TUESDAY {
            get {
                return ResourceManager.GetString("IDS_TUESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 三.
        /// </summary>
        public static string IDS_WEDNESDAY {
            get {
                return ResourceManager.GetString("IDS_WEDNESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作时间.
        /// </summary>
        public static string IDS_WORK_TIME {
            get {
                return ResourceManager.GetString("IDS_WORK_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LeftDown {
            get {
                object obj = ResourceManager.GetObject("LeftDown", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Normal {
            get {
                object obj = ResourceManager.GetObject("Normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
